clc;
clear;
close all;
load x1;
load x2;
load x3;
load x4;
load x5;
load x6;
load y1;
load y2;
figure;
plot(x1,y1,'LineWidth',2);
hold on;
plot(x2,y2);
hold on;
plot(x3,y2);
hold on;
plot(x4,y2);
hold on;
plot(x5,y2);
hold on;
 plot(x6,y2);
legend('vfpi','Hagedorn and brown','Beggs and brill','Ansari(slug)','Lockhart and Martinelli','Homogeneous Flow Model');
%legend('vfpi','Homogeneous Flow Model');
xlabel('Pressure(psia)');
ylabel('Measured Depth(ft)');